Fix overflow error and make filters usable
Change schemas.json to use long instead of int for host memory field,
avoiding this error:

    com.fasterxml.jackson.databind.JsonMappingException: Numeric value (50638880768) out of range of int

Replace the use of class Filters with Map<String,String> in service
templates, avoiding this error when calling list(filter) methods:

    java.lang.IllegalArgumentException: Map must include generic types